name: "Docker Deploy Action"
description: "Deploy Docker containers using GitHub Actions"
inputs:
  ssh-private-key:
    description: "SSH private key for server authentication"
    required: true
  server-ip:
    description: "Server IP address"
    default: "app.envoii.de"
  user:
    description: "SSH Username"
    default: "root"
  container-name:
    description: "Name of the container"
    required: true
  docker-compose-file:
    description: "Path to the Docker Compose file"
    default: "./docker-compose.yml"
  env-file:
    description: "Path to the environment file"
    default: "./.env-app"
runs:
  using: "composite"
  steps:
    - name: Deploy to Server
      shell: bash
      run: |
        mkdir -p ~/.ssh
        echo "${{ inputs.ssh-private-key }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa ${{ inputs.user }}@${{ inputs.server-ip }} << EOF
          cd /home/envoii
          docker compose -f ${{ inputs.docker-compose-file }} --project-directory ./ --env-file ${{ inputs.env-file }} up -d ${{ inputs.container-name }} --force-recreate --pull always
        EOF
