name: "Docker Deploy Action"
description: "Deploy Docker containers using GitHub Actions"
inputs:
  ssh-private-key:
    description: "SSH private key for server authentication"
    required: true
  server-ip:
    description: "Server IP address"
    default: "staging.envoii.de"
  user:
    description: "SSH Username"
    default: "root"
  container-name:
    description: "Name of the container"
    required: true
  docker-compose-file:
    description: "Path to the Docker Compose file"
    default: "./proxy/docker-compose.template.yml"
  env-file:
    description: "Path to the environment file"
    default: "./.env-stage"
runs:
  using: "composite"
  steps:
    - name: Deploy to Server
      shell: bash
      run: |
        ssh -o StrictHostKeyChecking=no -i ${{ inputs.ssh-private-key }} ${{ inputs.user }}@${{ inputs.server-ip }} << EOF
          cd /home/envoii
          docker compose -f ${{ inputs.docker-compose-file }} --project-directory ./ --env-file ${{ inputs.env-file }} up -d ${{container-name}} --force-recreate --pull always
        EOF
